name: Odds Scraper Run

on:
  push:
    paths:
      - 'target_link.txt'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run scraper
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }} # This connects your Secret to the code
        run: python scraper.py

      - name: Commit and Push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add results.json
          git commit -m "Update historical odds data" || exit 0
          git push
